### ISSUE TITLE
Excellent work. Are you using GitOps to sync code with running infrastructure??

### ISSUE THREAD

**Issue by rezuma** [ioos/Cloud-Sandbox#35]
This is very similar to what we have built and deploy for NASA Earth Information System. 
Great work.! Are you using GitOps approach to maintain the deployment? We are now deploying Flux and Crossplane to sync code<-->deployment

We are building additional Jlab extensions (to be open sourced) for the scientists that connect 
Jupyterhub to multiple public datasets in AWS, Azure, and Google Cloud, 
Turn any Notebook into a API endpoint (so you can public a NetCDF to Zarr endpoint, etc ) 
and connection of Notebooks to NLP AI

Very exciting and beneficial for the science community

**Comment by patrick-tripp** [comment]
Thanks for the comment. We are not using GitOps currently. I'll take a look at some of those tools though. Thanks.

Your work in JupyterHub sounds really great! I'll have to check it out.
