### ISSUE TITLE
rename default branch name from Master to Main

### ISSUE THREAD

**Issue by aliabdolali** [ioos/Cloud-Sandbox#49]
Github issued guidance on how-to and when-to rename the default branch name to be more inclusive and eliminate the use of **master**, which is offensive and derogatory. NOAA has started an effort to do such change and renamed master to **main** in most of the repositories. However, the sandbox is still using **master**. We need to change it to main. 

Github makes a guide for this
**[https://github.com/github/renaming](https://www.google.com/url?q=https://github.com/github/renaming&sa=D&source=docs&ust=1682370709440176&usg=AOvVaw2bhXj-aaFn3InNnP46cwS6)**

**Comment by mwengren** [comment]
@aliabdolali I agree we should make this change.   I've done this recently for several of our repositories and I'll go ahead and rename the branch now.  We've done this in many cases but not all IOOS repositories have been addressed yet.  

There are a few steps that anyone who has a local clone will need to do to keep in line with the repo once changed, and I'll copy those below once I make the change.

**Comment by mwengren** [comment]
This has been completed.  Some notes from GitHub for those working on the repo to update local clones/remote references:

Will update 1 pull request targeting this branch.
Will unpublish current GitHub Pages site.
Your current GitHub Pages site will become unpublished. A new commit on the renamed branch will publish the GitHub Pages site again.

Will not update your members' local environments.
Your members will have to manually update their local environments. We'll let them know when they visit the repository, or you can share the following commands:
```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

**Comment by aliabdolali** [comment]
awesome, thanks for the prompt reply.
