### ISSUE TITLE
LiveOcean configuration testing graphic

### ISSUE THREAD

**Issue by Michael-Lalime** [ioos/Cloud-Sandbox#78]
@ZacharyWills 
Tiffany has requested a graphic about the outcome.

Zach can you post your spreadsheet and early versions in here. I think the basic line graphics might be sufficient.

**Comment by ZacharyWills** [comment]
[Copy of Benchmark Testing for a 24 hour  - Data.csv](https://github.com/ioos/Cloud-Sandbox/files/14807981/Copy.of.Benchmark.Testing.for.a.24.hour.-.Data.csv)

Here's the cleaned up CSV.

Working indexing for time and for cost efficiency for the graphic(s).

**Comment by ZacharyWills** [comment]
<img width="1606" alt="Screenshot 2024-03-29 at 13 46 39" src="https://github.com/ioos/Cloud-Sandbox/assets/60660437/47fc688c-7cc1-4c5e-80d0-89d77d894394">

Table sorted by runtime

**Comment by Michael-Lalime** [comment]
[qofs_log.txt](https://github.com/ioos/Cloud-Sandbox/files/14808083/qofs_log.txt)
Copy of the output log runtimes.

**Comment by Michael-Lalime** [comment]
Is the table above the graphic or is the graphic something different that will be more like the first plot in the document you previously shared with examples: https://voltrondata.com/benchmarks/theseus ?

**Comment by Michael-Lalime** [comment]
[Copy_of_Benchmark_Testing_for_24-hour_Data.xlsx](https://github.com/ioos/Cloud-Sandbox/files/14808583/Copy_of_Benchmark_Testing_for_24-hour_Data.xlsx)
Working on this version, converted from the CSV. The barchart has instances with 1 node on the left and 4 on the right by type and number of minutes but it still needs labels and more work

**Comment by Michael-Lalime** [comment]
Test barchart with nodes 1-4, 1 on the left and 4 on the right. 
![image](https://github.com/ioos/Cloud-Sandbox/assets/75450912/be70fee1-69d5-408e-baea-b9bce7aef8c7)

**Comment by Michael-Lalime** [comment]
Closing issue as presentation was completed yesterday.
